server:
  port: 8088

spring:
  application:
    name: inventory-service
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/KaushikDBtest?createDatabaseIfNotExist=true
    username: root
    password: mmmmmm
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      default-binder: rabbit # Explicitly defining the default binder is good practice
      bindings:
        # Listens for 'userCreated' event from the user service
        userCreated-in-0:
          destination: user-events
          group: inventory-service
        userCreated-out-0:
          destination: user-events
      rabbit:
        bindings:
          userCreated-in-0:
            consumer:
              bindingRoutingKey: user.created

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true