server:
  port: 8081

spring:
  application:
    name: inventory
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=Demodb;encrypt=false
    username: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
     defaultBinder: rabbit
     bindings:
       userCreated-in-0:
         destination: user-events
         group: inventory-service
         contentType: application/json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

