server:
  port: 8082

spring:
  application:
    name: user-service
  profiles:
    active: local
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=Demodb;encrypt=false
    username: sa
    password: 123456
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        userCreated-out-0:
          destination: user-events
          content-type: application/json
        rollbackUser-in-0:
          destination: user-events
          group: user-service
      rabbit:
        bindings:
          rollbackUser-in-0:
            consumer:
              bindingRoutingKey: user.creation.failed

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
      springframework:
        orm:
          jpa: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true